version: "3.7"

services:
  web:
    #image: lnbitsdocker/lnbits
    image: lnbits
    #user: 1000:1000
    #init: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
            - "5000:5000"
    volumes:
      - ${PWD}/data:/app/data
      - ${PWD}/.env:/app/.env
    environment:
      FORWARDED_ALLOW_IPS: "*"
